services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed camwiley/udagram-api-feed:latest
  - docker tag udagram-api-user camwiley/udagram-api-user:latest
  - docker tag udagram-frontend camwiley/udagram-frontend:latest
  - docker tag reverseproxy camwiley/reverseproxy:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push camwiley/udagram-api-feed:latest
  - docker push camwiley/udagram-api-user:latest
  - docker push camwiley/udagram-frontend:latest
  - docker push camwiley/reverseproxy:latest
