apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  ports:
    - port: 8100
      protocol: TCP
      targetPort: 80
  selector:
    app: frontend
status:
  loadBalancer: {}
